# Generated by Django 3.1.5 on 2021-02-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('indexNo', models.CharField(max_length=7)),
                ('department', models.CharField(choices=[('EN', 'ENTC'), ('CS', 'CSE'), ('BM', 'BM'), ('ME', 'ME'), ('MT', 'MT'), ('CH', 'CH'), ('EE', 'EE'), ('CE', 'CE')], max_length=2)),
                ('contactNo', models.CharField(max_length=10)),
                ('image', models.ImageField(default='defaultDP.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
