# Generated by Django 3.1.5 on 2021-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210206_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='image',
            field=models.ImageField(default='profile_pics/defaultDP.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='profile_pics/defaultDP.jpg', upload_to='profile_pics'),
        ),
    ]
