# Generated by Django 3.1.5 on 2021-02-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210206_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='image',
            field=models.ImageField(default='defaultDP.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='defaultDP.jpg', upload_to='profile_pics'),
        ),
    ]
