# Generated by Django 3.1.5 on 2021-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210225_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.CharField(choices=[('EN', 'ENTC'), ('CS', 'CSE'), ('BM', 'BM'), ('ME', 'ME'), ('MT', 'MT'), ('CH', 'CH'), ('EE', 'EE'), ('CE', 'CE'), ('MA', 'MA')], max_length=2, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='image',
            field=models.ImageField(default='defaultDP.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contactNo',
            field=models.CharField(max_length=10, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('EN', 'ENTC'), ('CS', 'CSE'), ('BM', 'BM'), ('ME', 'ME'), ('MT', 'MT'), ('CH', 'CH'), ('EE', 'EE'), ('CE', 'CE')], max_length=2, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='defaultDP.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='indexNo',
            field=models.CharField(max_length=7, verbose_name='Index Number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
