# Generated by Django 3.1.5 on 2021-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='accept_status',
            field=models.CharField(choices=[('SD', 'Submission Deadline'), ('T2', 'TYPE2'), ('T3', 'TYPE3'), ('OT', 'Other')], max_length=2),
        ),
    ]
