# Generated by Django 3.1.5 on 2021-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0003_auto_20210212_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='accept_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('Rj', 'Rejected')], default='PD', max_length=2),
        ),
    ]
