# Generated by Django 3.1.5 on 2021-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0004_auto_20210212_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='accept_status',
            field=models.CharField(choices=[('PN', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='PN', max_length=2),
        ),
    ]
