# Generated by Django 3.1.5 on 2021-03-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requester', '0007_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='attachments',
            field=models.FileField(null=True, upload_to='request_attachments', verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='body',
            field=models.TextField(verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='content',
            field=models.TextField(verbose_name='Request Content'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reciever'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='requestType',
            field=models.CharField(choices=[('SD', 'Submission Deadline'), ('T2', 'TYPE2'), ('T3', 'TYPE3'), ('OT', 'Other')], max_length=2, verbose_name='Type of the request'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Request Title'),
        ),
    ]
