# Generated by Django 3.1.5 on 2021-03-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requester', '0008_auto_20210313_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='request_attachments', verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='reciever',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reciever'),
        ),
    ]
